#!/bin/bash

############################################################
#############----------CONFIGURATION------------############
############################################################

source /home/shrom/script/seedbox/include/sources.sh

sources;

#Utilisateur non-root qui utilisera rtorrent
USERNAME=$2

#Emplacement des fichiers de configuration et du dossier "session"
BASEPATH="/home/${USERNAME}"

#Emplacement du fichier de configuration du .rtorrent.rc
CONFIGPATH="${BASEPATH}/.rtorrent.rc"

#Nom usuel de la seedbox
SERVERNAME="seedbox.couillet.ovh"

#Nom du binaire de rtorrent 
SERVICE="rtorrent"

#Nom de la session tmux
SCRNAME=seedbox

#Options pour rtorrent
OPTIONS=""

############################################################
#############------END CONFIGURATION------------############
############################################################

## These are the parameters passed to the script
if [ $# -eq 2 ];
then
  case "$1" in
  'start')
    do_start;
    ;;
  'stop')
    do_stop;
    ;;
  'restart')
    do_restart;
    ;;
  'status')
    do_status;
    ;;
  'connect')
    do_connect;
    ;;
  *)
    echo "* usage: rtorrent {start|stop|restart|status|connect} username"
    exit 1;
    ;;
  esac
else
  echo "* usage: rtorrent {start|stop|restart|status|connect} username"
fi
exit 0;
